# import = ["~/.config/alacritty/catppuccin-mocha.toml"]
# import = ["~/.config/alacritty/material_theme_mod.toml"]
import = ["~/.config/alacritty/material.toml"]

[font]
size = 14.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[env]
TERM = "xterm-256color"
