theme = "custom"

[editor]
line-number = "relative"
indent-guides.render = true
continue-comments = false
# soft-wrap.enable = true

[keys.insert]
C-d = "normal_mode"
C-s = [":format", ":write", "normal_mode"]

[keys.normal]
C-s = [":format", ":write", "normal_mode"]
C-j = "save_selection"
# movement
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
# selection
X = "extend_line_above"
A-x = "extend_to_line_bounds"

[keys.normal."]"]
m.i = "@/[\\(\\[{]<ret>mim" 
m.a = "@/[\\(\\[{]<ret>mam" 

[keys.normal."["]
m.i = "@?[\\(\\[{]<ret>mim" 
m.a = "@?[\\(\\[{]<ret>mam" 

[keys.normal.space.u]
w = ":toggle soft-wrap.enable"
z = ":toggle gutters.line-numbers.min-width 50 3"

[keys.normal."space"]
q = ":q"
x = ":x"


