[[language]]
name = "typst"
language-servers = ["tinymist"]

[language-server.tinymist]
command = "tinymist"
config = { formatterMode = "typstyle" }

[[language]]
name = "coq"
scope = "source.coq"
grammar = "coq"
injection-regex = "coq"
file-types = ["v", "coq"]
roots = ["_CoqProject", "coq-pkgs"]
comment-token = "(*"
indent = { tab-width = 2, unit = "  " }
language-servers = ["coq-lsp"]

[language-server.coq-lsp]
command = "coq-lsp"

[[language]]
name = "markdown"
soft-wrap.enable = true
soft-wrap.wrap-at-text-width = true
soft-wrap.wrap-indicator = ""
language-servers = ["marksman", "harper"]

[language-server.harper]
command = "harper-ls"
args = ["--stdio"]
