#! /bin/sh

# start sxhkd
pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 0
bspc config window_gap 0

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

# set monocle by default
# for n in $(seq 1 5); do
# bspc desktop $n --layout monocle
# done

# remap keys
# setxkbmap -option "caps:ctrl_modifier"
# xcape -e "#66=Escape" &

# autostart applications
picom --config $HOME/.config/picom/picom.conf &
# nitrogen --restore &
dunst &
alacritty &
polybar -c ~/.config/polybar/config.ini -r main &
