#! /bin/sh

# setup monitors
sh ~/.config/setup/setup-monitors.sh

# start simple x hotkey daemon
pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

# set zero gap between windows
bspc config border_width 0
bspc config window_gap 0

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

# set monocle by default
# for n in $(seq 1 5); do
# bspc desktop $n --layout monocle
# done

# remap keys
# DEPRICATED: handled in kanata
# setxkbmap -option "caps:ctrl_modifier"
# xcape -e "#66=Escape" &

# autostart applications
picom --config $HOME/.config/picom/picom.conf & # window stylizer
# nitrogen --restore &
polybar -c ~/.config/polybar/config.ini -r main & # desktop info header
dunst &                                           # notifications
syncthing --no-browser &                          # file syncing
alacritty &                                       # terminal
