# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = hyperpaper &
# exec-once = gentoo-pipewire-launcher restart &
# exec-once = emacs --daemon
# exec-once = hyprswitch init --custom-css "/home/a/.config/hypr/hyprswitch.css"&

# start btop status terminal with smaller font size
exec-once = echo "font_size 10" > /tmp/btop-kitty.conf
exec-once = [workspace 1 silent] kitty --config /tmp/btop-kitty.conf -e btop
exec-once = [workspace 2 silent] $terminal
exec-once = [workspace 3 silent] ~/app/zen/zen
# exec-once = [workspace 4 silent] emacsclient -c

