# See https://wiki.hyprland.org/Configuring/Keywords/

# Set programs that you use
$terminal = ghostty
$menu     = fuzzel --config ~/.config/fuzzel/config.ini

$sessions = nu ~/.config/fuzzel/scripts/tmux-sessions.nu

$windows = nu ~/.config/fuzzel/scripts/hypr-windows.nu
# $windows = hyprswitch gui --mod-key super --key space --max-switch-offset 0
# $windows = hyprctl dispatch overview:toggle

$screenshot_dir = ~/doc/snp
$screenshot_window = hyprshot -m window -m active --clipboard-only
$screenshot_region = hyprshot -m region --clipboard-only
$screenshot_region_save = hyprshot -m region -o $screenshot_dir 
